// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// On the client (browser), route all Supabase traffic through the Next.js
// API proxy at /api/supabase to bypass regional domain blocking.
// On the server (SSR / API routes), connect directly to Supabase.
const SUPABASE_URL =
  typeof window !== "undefined"
    ? `${window.location.origin}/api/supabase`
    : process.env.SUPABASE_URL!;

const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
