// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getSupabaseUrl(): string {
  if (typeof window !== "undefined") {
    return `${window.location.origin}/api/supabase`;
  }
  return process.env.SUPABASE_URL!;
}

function getSupabaseKey(): string {
  return process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
}

// Lazy singleton — ensures the URL and key are evaluated at runtime
let _supabase: SupabaseClient<Database> | null = null;

function getClient(): SupabaseClient<Database> {
  if (!_supabase) {
    const url = getSupabaseUrl();
    const key = getSupabaseKey();
    if (!url || !key) {
      throw new Error(
        `Supabase config missing: url=${url ? "set" : "MISSING"}, key=${key ? "set" : "MISSING"}`
      );
    }
    _supabase = createClient<Database>(url, key, {
      auth: {
        storage: typeof window !== "undefined" ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  }
  return _supabase;
}

export const supabase: SupabaseClient<Database> = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop) {
    return (getClient() as any)[prop];
  },
});
