name: Deployment

on:

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'event-page'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          SUPABASE_URL: "https://cxvfoijklbwzzondmwuw.supabase.co"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4dmZvaWprbGJ3enpvbmRtd3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0NDE5ODcsImV4cCI6MjA4NDAxNzk4N30.qLkw6MG8hPMpjw3IFDlWV6KqSqS_bFd5uIWh1YcQTQc"
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.next'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
